server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/misafir
    username: oguz
    password: oguz
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Multipart file upload settings
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.web: DEBUG
